apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 4.5.0
    releaseName: jenkins
    namespace: jenkins
    valuesFile: values.yaml
